### ISSUE TITLE
New record type: scan statistics

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ts/CxAnalytix#129]
### Describe the problem

Newer versions of SAST have a scan statistics API (/cxrestapi/sast/scans/{id}/statistics) that should be a new record type.

### Proposed solution

Each scan has a statistics result, and each result has aggregate contents (e.g. product version, engine version, memory peak, etc) but also has breakdowns by language.  Flatten by language type so that there is one record entry per language.

**Comment by nirw** [comment]
yes please!
