### ISSUE TITLE
Date parsing error in non-US locale

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ts/CxAnalytix#20]
### Description

The CxAnalytix crawl fails due to a date parsing error when run on a machine with a non-US locale.

### Expected Behavior

Dates from the server should be parsed without failure.

### Actual Behavior
Date parsing fails with an error:

```
System.FormatException: String '08/13/2020 00:02:37' was not recognized as a valid DateTime.
```

### Reproduction

Set the client in a non-US display locale, such as Austrailia, that uses a different date format. 

### Environment Details

The locale of the server does not appear to format the date according to the display rules.  The server appears to send the date in the US locale format regardless of the server-side locale.

**Comment by udaykor** [comment]
@nleach999  hotfix/issue20-date-parsing-error solves the non-us Locale. This can be merged to master
